// leave off @2x/@3x
const images = {
    mealerLogo: require('../Images/mealer_logo.png'),
    logo: require('../Images/app_logo.png'),
    clearLogo: require('../Images/top_logo.png'),
    launch: require('../Images/launch-icon.png'),
    ready: require('../Images/your-app.png'),
    ignite: require('../Images/ignite_logo.png'),
    igniteClear: require('../Images/ignite-logo-transparent.png'),
    tileBg: require('../Images/tile_bg.png'),
    background: require('../Images/BG.png'),
    buttonBackground: require('../Images/button-bg.png'),
    api: require('../Images/Icons/icon-api-testing.png'),
    components: require('../Images/Icons/icon-components.png'),
    deviceInfo: require('../Images/Icons/icon-device-information.png'),
    faq: require('../Images/Icons/faq-icon.png'),
    home: require('../Images/Icons/icon-home.png'),
    theme: require('../Images/Icons/icon-theme.png'),
    usageExamples: require('../Images/Icons/icon-usage-examples.png'),
    chevronRight: require('../Images/Icons/chevron-right.png'),
    hamburger: require('../Images/Icons/hamburger.png'),
    backButton: require('../Images/Icons/back-button.png'),
    closeButton: require('../Images/Icons/close-button.png'),

    settingsColor: require('../Images/Icons/icon_settings_color.png'),
    settingsWhite: require('../Images/Icons/icon_settings_white.png'),
    cooksColor: require('../Images/Icons/icon_cooks_color.png'),
    cooksWhite: require('../Images/Icons/icon_cooks_white.png'),
    ordersColor: require('../Images/Icons/icon_orders_color.png'),
    ordersWhite: require('../Images/Icons/icon_orders_white.png'),
    infoIcon: require('../Images/Icons/info_icon.png'),
    menuWhite: require('../Images/Icons/icon_menu_white.png'),
    biryani: require('../Images/biryani.png'),
    addItemImage: require('../Images/add_item_image.png'),
    addItemImage2x: require('../Images/add_item_image_2x.png'),
    addImagePlaceHolder: require('../Images/add-image-placeholder-icon.jpg'),
    emptyCart: require('../Images/empty-cart.png'),
};

export default images
